package com.example.sfchat.item;

/**
 * Created by mac on 16/11/27.
 */

public enum  ChatViewType {

    MSG_LEFT_TXT,MSG_RIGHT_TXT,MSG_LEFT_PHOTO,MSG_RIGHT_PHOTO,MSG_LEFT_LOCATION,MSG_RIGHT_LOCATION,
    MSG_LEFT_GIF,MSG_RIGHT_GIF,MSG_LEFT_AUDIO,MSG_RIGHT_AUDIO,MSG_LEFT_PAPER,MSG_RIGHT_PAPER;
}
